name: hangisi_app
description: "Mobil Programlama Final Ödevi"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0  # 3.9.2 henüz çıkmadı, stabil sürüm yapıldı (değiştirebilirsiniz)

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.1.0
  provider: ^6.1.1

  # Firebase paketleri
  firebase_core: ^3.10.1
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.1
  firebase_storage: ^12.4.10
  
  # Diğer özellikler
  mobile_scanner: ^5.1.1
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Sadece klasör adını yazmak yeterlidir, içindekileri otomatik görür.
  assets:
    - assets/
   