name: hangisi_app
description: "Mobil Programlama Final Ödevi"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Google Fontları (iOS benzeri Inter fontu için)
  google_fonts: ^6.1.0

  # State Management (Durum Yönetimi)
  provider: ^6.1.1

  # Firebase (Veritabanı ve Giriş için)
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/