name: hangisi_app
description: "Mobil Programlama Final Ödevi"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.1.0
  provider: ^6.1.1

  # Birbiriyle uyumlu test edilmiş Firebase sürümleri:
  firebase_core: ^3.10.1
  firebase_auth: ^5.7.0     # Çakışmayı gidermek için bu sürüme çekildi
  cloud_firestore: ^5.6.1
  firebase_storage: ^12.4.10
  mobile_scanner: ^5.1.1
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/inekler.png
    - assets/logo.png
    - assets/splash_arkaplan.png
    - assets/tuketici.png
    - assets/uretici.png